Home/urls.py
__author__ = 'Behnam Hatami'

from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^home$', 'Home.views.home', name="home"),
                       )

Management/urls.py
__author__ = 'Behnam Hatami'

from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^home$', 'Management.views.home', name='home'),
                       url(r'^strategy/create$', 'Management.views.create_strategy', name='create_strategy'),
                       url(r'^strategy/(?P<stid>\d+)/edit$', 'Management.views.edit_strategy', name='edit_strategy'),
                       url(r'^strategy/(?P<stid>\d+)/delete$', 'Management.views.delete_strategy',
                           name='delete_strategy'),
                       url(r'^strategy/(?P<stid>\d+)$', 'Management.views.view_strategy', name='view_strategy'),
                       url(r'^strategy$', 'Management.views.strategy', name='strategy'),
                       url(r'^plan/create$', 'Management.views.create_plan', name='create_plan'),
                       url(r'^plan/(?P<pid>\d+)/edit$', 'Management.views.edit_plan', name='edit_plan'),
                       url(r'^plan/(?P<pid>\d+)/delete$', 'Management.views.delete_plan', name='delete_plan'),
                       url(r'^plan/(?P<pid>\d+)$', 'Management.views.view_plan', name='view_plan'),
                       url(r'^plan$', 'Management.views.plan', name='plan'),
)

Pasargad/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Pasargad.views.home', name='home'),
    # url(r'^Pasargad/', include('Pasargad.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('Account.urls', namespace='Account')),
    url(r'^insurance/', include('Insurance.urls', namespace='Insurance')),
    url(r'^management/', include('Management.urls', namespace='Management')),
    url(r'^Accident/', include('Accident.urls', namespace='Accident')),
    url(r'^Statistic/', include('Statistic.urls', namespace='Statistic')),
    url(r'^', include('Home.urls', namespace='Home')),
)

Home/models.py
from django.db import models

# Create your models here.

Management/models.py
# Create your models here.

Management/forms.py
__author__ = 'Behnam'
from django.forms import ModelForm
from django import forms
from django.utils.translation import ugettext_lazy as _

from Insurance.models import *


class Insurance_type_show_form(ModelForm):
    class Meta:
        model = Insurance_type
        exclude = ()


class Insurance_type_edit_form(ModelForm):
    class Meta:
        model = Insurance_type
        exclude = ('id', )


class Insurance_plan_show_form(ModelForm):
    class Meta:
        model = Insurance_plan
        exclude = ('id', )


class Insurance_plan_edit_form(ModelForm):
    class Meta:
        model = Insurance_plan
        exclude = ('id', )

Home/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from Pasargad.helper import *


def home(request):
    error_message = ''

    if not request.user.is_authenticated():
        if request.method.upper() == 'POST':
            username = request.POST['username']
            password = request.POST['password']

            user = authenticate(username=username, password=password)
            if user is None:
                error_message = 'The username or password you entered is incorrect.'
            elif not user.is_active:
                error_message = 'The user has been disabled by admin.'

            if error_message != '':
                return render(request, 'Home/Signin.html', {
                    'error_message': error_message,
                })
            login(request, user)
            if request.GET.__contains__("next"):
                return redirect(request.GET.get("next"))
            else:
                return redirect('Home:home')
        else:
            return render(request, 'Home/Signin.html')
    else:
        print(get_user_name(request))
        return render(request, 'Home/home.html', {
            'user_name': get_user_name(request),
            'security': get_security(request)
        })

Management/views.py
from django.contrib.auth.decorators import login_required
from django.forms.models import modelformset_factory
from django.shortcuts import render, redirect, get_object_or_404
from Insurance.models import *
from Pasargad.helper import *
from Management.forms import *


@login_required
@group_required(Admin, Secretory, Expert)
def home(request):
    return render(request, 'Management/home.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
    })


@login_required
@group_required(Admin, Secretory, Expert)
def strategy(request):
    queryset = Insurance_type.objects.all()
    form_head = Insurance_type_show_form()
    property_set = []
    for item in queryset:
        property_set.append(get_property_list(item, form_head, id=item.id))
    return render(request, 'Management/strategy.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'form_head': form_head,
        'property_set': property_set,
        'notify_message': "There isn't any strategy" if len(property_set) == 0 else '',
    })


@login_required
@group_required(Admin)
def create_strategy(request):
    success_message = None

    if request.method.upper() == 'POST':
        form = Insurance_type_show_form(request.POST)
        if form.is_valid():
            form.save()
            success_message = "Insurance strategy added."
        else:
            pass
    else:
        form = Insurance_type_show_form()

    return render(request, 'Management/create_strategy.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'form': form,
        'success_message': success_message,
    })


@login_required
@group_required(Admin, Secretory, Expert)
def view_strategy(request, stid):
    strategy = get_object_or_404(Insurance_type, pk=stid)
    form = Insurance_type_show_form(instance=strategy)

    return render(request, 'Management/view_strategy.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'strategy_id': stid,
        'property_list': get_property_list(strategy, form, id=strategy.id),
    })


@login_required
@group_required(Admin)
def edit_strategy(request, stid):
    success_message = None
    form = None

    strategy = get_object_or_404(Insurance_type, pk=stid)
    if request.method.upper() == 'POST':
        form = Insurance_type_show_form(request.POST, instance=strategy)
        if form.is_valid():
            form.save()
            success_message = "Changes applied."
    else:
        form = Insurance_type_show_form(instance=strategy)

    return render(request, 'Management/edit_strategy.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'form': form,
        'strategy_id': stid,
        'success_message': success_message,
    })


@login_required
@group_required(Admin)
def delete_strategy(request, stid):
    strategy = get_object_or_404(Insurance_type, pk=stid)

    if request.method.upper() == 'POST':
        strategy.delete()
        return redirect('Management:strategy')

    return render(request, 'Management/delete_strategy.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'strategy': strategy,
    })


@login_required
@group_required(Admin, Secretory, Expert)
def plan(request):
    queryset = Insurance_plan.objects.all()
    form_head = Insurance_plan_show_form()
    property_set = []
    for item in queryset:
        property_set.append(get_property_list(item, form_head, item.id))
    return render(request, 'Management/plan.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'form_head': form_head,
        'property_set': property_set,
        'notify_message': "There isn't any plan" if len(property_set) == 0 else '',
    })


@login_required
@group_required(Admin)
def create_plan(request):
    success_message = None

    if request.method.upper() == 'POST':
        form = Insurance_plan_show_form(request.POST)
        if form.is_valid():
            form.save()
            success_message = "Insurance plan added."
            for name in form.fields:
                form.fields[name].widget.attrs['readonly'] = True
        else:
            pass
    else:
        form = Insurance_plan_show_form()

    return render(request, 'Management/create_plan.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'form': form,
        'success_message': success_message,
    })


@login_required
@group_required(Admin, Secretory, Expert)
def view_plan(request, pid):
    plan = get_object_or_404(Insurance_plan, pk=pid)
    form = Insurance_plan_show_form(instance=plan)
    return render(request, 'Management/view_plan.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'plan_id': pid,
        'property_list': get_property_list(plan, form, id=plan.id),
    })


@login_required
def edit_plan(request, pid):
    success_message = None
    form = None

    plan = get_object_or_404(Insurance_plan, pk=pid)
    if request.method.upper() == 'POST':
        form = Insurance_plan_show_form(request.POST, instance=plan)
        if form.is_valid():
            form.save()
            success_message = "Changes applied."
    else:
        form = Insurance_plan_show_form(instance=plan)

    return render(request, 'Management/edit_plan.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'form': form,
        'plan_id': pid,
        'success_message': success_message,
    })


@login_required
@group_required(Admin)
def delete_plan(request, pid):
    plan = get_object_or_404(Insurance_plan, pk=pid)

    if request.method.upper() == 'POST':
        plan.delete()
        return redirect('Management:plan')

    return render(request, 'Management/delete_plan.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'plan': plan,
    })

Management/templates/Management/create_plan.html
{% extends "Management/management_base.html" %}
{% block navbar_title %} Create Plan {% endblock %}
{% block sidebar_create_plan %}active{% endblock %}
{% block sidebar_back %}{% url 'Management:home' %}{% endblock %}
{% block content %}
    <div class="container">
        <form class="form-horizontal" style="width: 400px;" method="POST">
            {% csrf_token %}
            <hr>
            <table style="background: #ededff" class="table table-bordered">
                <colgroup>
                    <col class="col1">
                    <col class="col2">
                </colgroup>
                <tbody>
                {{ form.as_table }}
                </tbody>
            </table>
            <hr>
            <button class="btn btn-success" type="submit">Save</button>
            <a class="btn btn-danger" href="{% url 'Management:home' %}">Cancel</a>
            <a class="btn btn-warning" href="{% url 'Management:create_plan' %}">Reset</a>
        </form>
    </div>
{% endblock %}

Management/templates/Management/create_strategy.html
{% extends "Management/management_base.html" %}
{% block navbar_title %} Create strategy {% endblock %}
{% block sidebar_create_strategy %}active{% endblock %}
{% block sidebar_back %}{% url 'Management:home' %}{% endblock %}
{% block content %}
    <div class="container">
        <form class="form-horizontal" style="width: 400px;" method="POST">
            {% csrf_token %}
            <hr>
            <table style="background: #ededff" class="table table-bordered">
                <colgroup>
                    <col class="col1">
                    <col class="col2">
                </colgroup>
                <tbody>
                {{ form.as_table }}
                </tbody>
            </table>
            <hr>
            <button class="btn btn-success" type="submit">Save</button>
            <a class="btn btn-danger" href="{% url 'Management:home' %}">Cancel</a>
            <a class="btn btn-warning" href="{% url 'Management:create_strategy' %}">Reset</a>
        </form>
    </div>
{% endblock %}

Management/templates/Management/delete_plan.html
{% extends "Management/management_base.html" %}
{% block navbar_title %} Delete strategy {% endblock %}
{% block sidebar_plan %}active{% endblock %}
{% block sidebar_back %}{% url 'Management:view_plan' plan.id %}{% endblock %}

{% block content %}
    {% if plan %}
        <div class="container">
            <form class="form-horizontal" style="width: 400px;" method="POST">
                {% csrf_token %}
                <hr>
                <p>
                    Are you sure you want to delete the insurance plan named {{ plan.name }}?
                </p>
                <button class="btn btn-danger" type="submit">Confirm</button>
                <a class="btn btn-warning" href="{% url 'Management:view_plan' plan.id %}">Cancel</a>
            </form>
        </div>
    {% endif %}
{% endblock %}

Management/templates/Management/delete_strategy.html
{% extends "Management/management_base.html" %}
{% block navbar_title %} Delete strategy {% endblock %}
{% block sidebar_strategy %}active{% endblock %}
{% block sidebar_back %}{% url 'Management:view_strategy' strategy.id %}{% endblock %}

{% block content %}
    {% if strategy %}
        <div class="container">
            <form class="form-horizontal" style="width: 400px;" method="POST">
                {% csrf_token %}
                <hr>
                <p>
                    Are you sure you want to delete the insurance plan named {{ strategy.name }}?
                </p>
                <button class="btn btn-danger" type="submit">Confirm</button>
                <a class="btn btn-warning" href="{% url 'Management:view_strategy' strategy.id %}">Cancel</a>
            </form>
        </div>
    {% endif %}
{% endblock %}

Management/templates/Management/edit_plan.html
{% extends "Management/management_base.html" %}
{% block navbar_title %}Edit Plan{% endblock %}
{% block sidebar_plan %}active{% endblock %}
{% block sidebar_back %}{% url 'Management:view_plan' plan_id %}{% endblock %}

{% block content %}
    {% if form %}
        <div class="container">
            <form class="form-horizontal" style="width: 400px;" method="POST">
                {% csrf_token %}
                <hr>
                <table style="background: #ededff" class="table table-bordered">
                    <colgroup>
                        <col class="col1">
                        <col class="col2">
                    </colgroup>
                    <tbody>
                    {{ form.as_table }}
                    </tbody>
                </table>
                <button class="btn btn-success" type="submit">Save</button>
                <a class="btn btn-danger" href="{% url 'Management:view_plan' plan_id %}">Cancel</a>
                <a class="btn btn-warning" href="{% url 'Management:edit_plan' plan_id %}">Reset</a>
            </form>
        </div>
    {% endif %}
{% endblock %}

Management/templates/Management/edit_strategy.html
{% extends "Management/management_base.html" %}
{% block navbar_title %} Edit strategy {% endblock %}
{% block sidebar_strategy %}active{% endblock %}
{% block sidebar_back %}{% url 'Management:view_strategy' strategy_id %}{% endblock %}

{% block content %}
    {% if form %}
        <div class="container">
            <form class="form-horizontal" style="width: 400px;" method="POST">
                {% csrf_token %}
                <hr>
                <table style="background: #ededff" class="table table-bordered">
                    <colgroup>
                        <col class="col1">
                        <col class="col2">
                    </colgroup>
                    <tbody>
                    {{ form.as_table }}
                    </tbody>
                </table>
                <button class="btn btn-success" type="submit">Save</button>
                <a class="btn btn-danger" href="{% url 'Management:view_strategy' strategy_id %}">Cancel</a>
                <a class="btn btn-warning" href="{% url 'Management:edit_strategy' strategy_id %}">Reset</a>
            </form>
        </div>
    {% endif %}
{% endblock %}

Management/templates/Management/home.html
{% extends "home_base.html" %}

{% block navbar_title %} System Management {% endblock %}
{% block sidebar_management %}active{% endblock %}
{% block navbar_management %}active{% endblock %}
{% block sidebar_back %}{% url 'Home:home' %}{% endblock %}
{% block content %}
    <div class="row-fluid">
        <div class="span4">
            <h2>Strategy</h2>

            <p>Have a quick look on the strategies that are defined. You can easily see the details of each of them and
            introduce new strategies to your insurance system.</p>
            <p><a class="btn" href="{% url 'Management:strategy' %}">Go to the strategy sub-system &raquo;</a></p>
        </div>
        <!--/span-->
        <div class="span4">
            <h2>Plan</h2>

            <p>Have a quick look on the plans that are defined. Add new plans using the introduced strategies and edit
                 easily using the plan system.</p>
            <p><a class="btn" href="{% url 'Management:plan' %}">Go to the plan sub-system &raquo;</a></p>
        </div>
        <!--/span-->
    </div><!--/row-->
{% endblock %}

Management/templates/Management/management_base.html
{% extends "base.html" %}
{% block sidebar_back %}{% url 'Management:home' %}{% endblock %}
{% block navbar_management %}active{% endblock %}
{% block sidebar_content %}
    <li class="{% block sidebar_strategy %}{% endblock %}"><a href="{% url 'Management:strategy' %}">Strategy</a></li>
    <li class="{% block sidebar_create_strategy %}{% endblock %}"><a href="{% url 'Management:create_strategy' %}">Create
        Strategy</a></li>
    <li class="{% block sidebar_plan %}{% endblock %}"><a href="{% url 'Management:plan' %}">Plan</a></li>
    <li class="{% block sidebar_create_plan %}{% endblock %}"><a href="{% url 'Management:create_plan' %}">Create
        Plan</a>
    </li>
{% endblock %}

Management/templates/Management/plan.html
{% extends 'Management/management_base.html' %}
{% block navbar_title %}Plan{% endblock %}
{% block sidebar_plan %}active{% endblock %}
{% block sidebar_back %}{% url 'Management:home' %}{% endblock %}
{% block content %}
    {% if not notify_message %}
        <hr>
        <table style="background: #ededff" class="table table-bordered">
            <colgroup>
                <col class="col1">
                <col class="col2">
            </colgroup>
            <thead>
            <tr>
                {% for field in form_head %}
                    <th><b>{{ field.label|capfirst }}</b></th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for property_list in property_set %}
                <tr>
                    {% for property in property_list %}
                        {% if property.0 != 'Name' %}
                            <td>
                                <lable>{{ property.1|linebreaksbr }}</lable>
                            </td>
                        {% else %}
                            <td><label><a
                                    href="{% url 'Management:view_plan' property_list.id %}">{{ property.1|linebreaksbr }}</a></label>
                            </td>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

Management/templates/Management/strategy.html
{% extends 'Management/management_base.html' %}
{% block navbar_title %} Strategy {% endblock %}
{% block sidebar_strategy %}active{% endblock %}
{% block sidebar_back %}{% url 'Management:home' %}{% endblock %}
{% block content %}
    {% if not notify_message %}
        <hr>
        <table style="background: #ededff" class="table table-bordered">
            <colgroup>
                <col class="col1">
                <col class="col2">
            </colgroup>
            <thead>
            <tr>
                {% for field in form_head %}
                    <th><b>{{ field.label|capfirst }}</b></th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for property_list in property_set %}
                <tr>
                    {% for property in property_list %}
                        {% if property.0 != 'Name' %}
                            <td>
                                <lable>{{ property.1|linebreaksbr }}</lable>
                            </td>
                        {% else %}
                            <td><label><a
                                    href="{% url 'Management:view_strategy' property_list.id %}">{{ property.1|linebreaksbr }}</a></label>
                            </td>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

Management/templates/Management/view_plan.html
{% extends "Management/management_base.html" %}
{% block navbar_title %} View Plan {% endblock %}
{% block sidebar_plan %}active{% endblock %}
{% block sidebar_back %}{% url 'Management:plan' %}{% endblock %}
{% block content %}
    <div class="container">
        <form class="form-horizontal" style="width: 500px;" method="POST">
            {% csrf_token %}
            <hr>
            <table style="background: #ededff" class="table table-bordered">
                <colgroup>
                    <col class="col1">
                    <col class="col2">
                </colgroup>
                <tbody>
                <tr>
                    <td><label>ID Number</label></td>
                    <td><label>{{ property_list.id }}</label></td>
                </tr>
                {% for property in property_list %}
                    <tr>
                        <td><label>{{ property.0 }}</label></td>
                        <td><label>{{ property.1|linebreaksbr }}</label></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <a class="btn btn-warning" type="submit"
               href="{% url 'Management:edit_plan'  plan_id %}">Edit</a>
            <a class="btn btn-danger" type="submit"
               href="{% url 'Management:delete_plan'  plan_id %}">Delete</a>
        </form>
    </div>
{% endblock %}

Management/templates/Management/view_strategy.html
{% extends "Management/management_base.html" %}
{% block navbar_title %} View strategy {% endblock %}
{% block sidebar_strategy %}active{% endblock %}
{% block sidebar_back %}{% url 'Management:strategy' %}{% endblock %}
{% block content %}
    <div class="container">
        <form class="form-horizontal" style="width: 400px;" method="POST">
            {% csrf_token %}
            <hr>
            <table style="background: #ededff" class="table table-bordered">
                <colgroup>
                    <col class="col1">
                    <col class="col2">
                </colgroup>
                <tbody>
                <tr>
                    <td><label>ID Number</label></td>
                    <td><label>{{ property_list.id }}</label></td>
                </tr>
                {% for property in property_list %}
                    <tr>
                        <td><label>{{ property.0 }}</label></td>
                        <td><label>{{ property.1|linebreaksbr }}</label></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <a class="btn btn-warning" type="submit"
               href="{% url 'Management:edit_strategy'  strategy_id %}">Edit</a>
            <a class="btn btn-danger" type="submit"
               href="{% url 'Management:delete_strategy'  strategy_id %}">Delete</a>
        </form>
    </div>
{% endblock %}