Accident/urls.py
__author__ = 'Behnam Hatami'

from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^home$', 'Accident.views.home', name="home"),
                       url(r'^create_accident$', 'Accident.views.create_accident', name='create_accident'),
                       url(r'^(?P<aid>\d+)/finalize$', 'Accident.views.finalize_accident', name='finalize_accident'),
                       url(r'^(?P<aid>\d+)/$', 'Accident.views.view_accident', name='view_accident'),
                       url(r'^$', 'Accident.views.accident', name='accident'),
)

Home/urls.py
__author__ = 'Behnam Hatami'

from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^home$', 'Home.views.home', name="home"),
                       )

Pasargad/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Pasargad.views.home', name='home'),
    # url(r'^Pasargad/', include('Pasargad.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('Account.urls', namespace='Account')),
    url(r'^insurance/', include('Insurance.urls', namespace='Insurance')),
    url(r'^management/', include('Management.urls', namespace='Management')),
    url(r'^Accident/', include('Accident.urls', namespace='Accident')),
    url(r'^Statistic/', include('Statistic.urls', namespace='Statistic')),
    url(r'^', include('Home.urls', namespace='Home')),
)

Statistic/urls.py
__author__ = 'Behnam Hatami'

from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^home$', 'Statistic.views.home', name='home'),
                       url(r'^general$', 'Statistic.views.general_payments', name='general'),
                       url(r'^user$', 'Statistic.views.user_payments', name='user'),
                       url(r'owner$', 'Statistic.views.owner_payments', name='owner'),
                       url(r'accidents', 'Statistic.views.accidents', name='accident'),
)

Accident/models.py
from django.db import models

# Create your models here.

Home/models.py
from django.db import models

# Create your models here.

Accident/forms.py
__author__ = 'Behnam Hatami'
from django import forms
from django.forms import ModelForm
from django.forms.widgets import TextInput
from django.utils.translation import ugettext_lazy as _

from Insurance.models import *


class accident_form_show(ModelForm):
    class Meta:
        model = Accident
        exclude = ('id', 'payment')


class payment_form_show(ModelForm):
    class Meta:
        model = Payment
        exclude = ('id', )


class report_form_show(ModelForm):
    class Meta:
        model = Report
        exclude = ('id', )


class report_form_edit(ModelForm):
    class Meta:
        model = Report
        exclude = ('id', 'date', 'accident')


class search_accident_form(forms.Form):
    error_messages = {
        'not_exist': _("No Accident with this ID exists."),
    }

    accident = forms.IntegerField(required=True)

    def clean_accident(self):
        accident = self.cleaned_data["accident"]
        if accident:
            try:
                Accident.objects.get(pk=accident)
            except:
                raise forms.ValidationError(self.error_messages['not_exist'])
        return accident


class accident_form_create(ModelForm):
    class Meta:
        model = Accident
        exclude = ('payment',)
        widgets = {
            'vehicle': TextInput(),
        }

Accident/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from Pasargad.helper import *
from Accident.forms import *


@login_required
@group_required(Secretory, Expert)
def home(request):
    return render(request, 'Accident/home.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
    })


@login_required
@group_required(Secretory)
def create_accident(request):
    if request.method.upper() == 'GET':
        form = accident_form_create()
    else:
        form = accident_form_create(request.POST)
        if form.is_valid():
            accident = form.save()
            return redirect('Accident:view_accident', accident.id)

    return render(request, 'Accident/create_accident.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'form': form,
    })


@login_required
@group_required(Secretory, Expert)
def view_accident(request, aid):
    accident = get_object_or_404(Accident, pk=aid)
    property_set = [get_property_list(accident, accident_form_show(), id=aid, title='Accident')]

    if accident.get_report() is not None:
        property_set.append(
            get_property_list(accident.get_report(), report_form_show(), id=accident.get_report().id, title='Report'))

    if accident.payment is not None:
        property_set.append(
            get_property_list(accident.payment, payment_form_show(), id=accident.payment.id, title='Payment'))

    return render(request, 'Accident/view_accident.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'accident_id': aid,
        'property_set': property_set,
    })


@login_required
@group_required(Expert)
def finalize_accident(request, aid):
    form = None
    accident = get_object_or_404(Accident, pk=aid)

    if request.method.upper() == 'POST':
        report_instance = Report(date=timezone.now(), accident=accident)
        form = report_form_edit(request.POST, instance=report_instance)
        if form.is_valid():
            form.save()
            payment = Payment(cost=-form.cleaned_data['cost'], date=report_instance.date, dealer=request.user,
                              owner=accident.vehicle.vehicle_owner)
            payment.save()
            accident.payment = payment
            accident.save()
            return redirect('Accident:view_accident', aid=aid)
    else:
        form = report_form_edit()

    return render(request, 'Accident/finalize_accident.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'accident_id': aid,
        'form': form,
    })


@login_required
@group_required(Expert, Secretory)
def accident(request):
    form = None
    if request.method.upper() == 'POST':
        form = search_accident_form(request.POST)
        if form.is_valid():
            return redirect('Accident:view_accident', aid=form.cleaned_data['accident'])
    else:
        form = search_accident_form()

    return render(request, 'Accident/search_accident.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'form': form,
    })

Home/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from Pasargad.helper import *


def home(request):
    error_message = ''

    if not request.user.is_authenticated():
        if request.method.upper() == 'POST':
            username = request.POST['username']
            password = request.POST['password']

            user = authenticate(username=username, password=password)
            if user is None:
                error_message = 'The username or password you entered is incorrect.'
            elif not user.is_active:
                error_message = 'The user has been disabled by admin.'

            if error_message != '':
                return render(request, 'Home/Signin.html', {
                    'error_message': error_message,
                })
            login(request, user)
            if request.GET.__contains__("next"):
                return redirect(request.GET.get("next"))
            else:
                return redirect('Home:home')
        else:
            return render(request, 'Home/Signin.html')
    else:
        print(get_user_name(request))
        return render(request, 'Home/home.html', {
            'user_name': get_user_name(request),
            'security': get_security(request)
        })

Statistic/views.py
import json
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from Insurance.models import Payment, Accident
from Pasargad.helper import group_required, get_user_name, get_security, Admin
from Statistic.forms import general_form, user__form, owner__form
from Statistic.utils import get_count_report, get_payment_report


@login_required
@group_required(Admin)
def home(request):
    return render(request, 'Statistics/home.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
    })


@login_required
@group_required(Admin)
def general_payments(request):
    chart = None
    if request.method.upper() == 'GET':
        form = general_form()
    else:
        form = general_form(request.POST)
        if form.is_valid():
            report = get_payment_report(Payment.objects.all(), form)
            from_date = form.cleaned_data['from_date']
            to_date = form.cleaned_data['to_date']
            title = "Total Income And Expenditure Of {} From {} To {}".format('Pasargad Insurance', from_date, to_date)
            chart = [{"series": [{"stacking": False, "data": report[1], "type": "line", "name": "Expenditure"},
                                 {"stacking": False, "data": report[2], "type": "line", "name": "Income"}],
                      "yAxis": [{"title": {"text": "Income & Expenditure "}}], "chart": {"renderTo": "chart"},
                      "xAxis": [{"categories": report[0], "title": {"text": "Dates"}}],
                      "title": {"text": title}}]
            chart = json.dumps(chart)

    return render(request, 'Statistics/general.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'form': form,
        'chart': chart,
    })


@login_required
@group_required(Admin)
def user_payments(request):
    chart = None
    if request.method.upper() == 'GET':
        form = user__form()
    else:
        form = user__form(request.POST)
        if form.is_valid():
            user = form.cleaned_data['user']
            report = get_payment_report(Payment.objects.all().filter(dealer=user), form)
            from_date = form.cleaned_data['from_date']
            to_date = form.cleaned_data['to_date']
            title = "Total Income And Expenditure Of {} From {} To {}".format(user, from_date, to_date)
            chart = [{"series": [{"stacking": False, "data": report[1], "type": "line", "name": "Expenditure"},
                                 {"stacking": False, "data": report[2], "type": "line", "name": "Income"}],
                      "yAxis": [{"title": {"text": "Expenditure & Income"}}], "chart": {"renderTo": "chart"},
                      "xAxis": [{"categories": report[0], "title": {"text": "Dates"}}],
                      "title": {"text": title}}]
            chart = json.dumps(chart)

    return render(request, 'Statistics/user.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'form': form,
        'chart': chart,
    })


@login_required
@group_required(Admin)
def accidents(request):
    chart = None
    if request.method.upper() == 'GET':
        form = general_form()
    else:
        form = general_form(request.POST)
        if form.is_valid():
            report = get_count_report(Accident.objects.all(), form)
            from_date = form.cleaned_data['from_date']
            to_date = form.cleaned_data['to_date']
            title = "Total Accident From {} To {}".format(from_date, to_date)
            chart = [{"series": [{"stacking": False, "data": report[1], "type": "line", "name": "Expenditure"}],
                      "yAxis": [{"title": {"text": "Count"}}], "chart": {"renderTo": "chart"},
                      "xAxis": [{"categories": report[0], "title": {"text": "Dates"}}],
                      "title": {"text": title}}]
            chart = json.dumps(chart)

    return render(request, 'Statistics/accident.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'form': form,
        'chart': chart,
    })


@login_required
@group_required(Admin)
def owner_payments(request):
    chart = None
    if request.method.upper() == 'GET':
        form = owner__form()
    else:
        form = owner__form(request.POST)
        if form.is_valid():
            owner = form.cleaned_data['owner']
            report = get_payment_report(Payment.objects.all().filter(owner=owner), form)
            from_date = form.cleaned_data['from_date']
            to_date = form.cleaned_data['to_date']
            title = "Total Income And Expenditure Of {} From {} To {}".format(owner, from_date, to_date)
            chart = [{"series": [{"stacking": False, "data": report[1], "type": "line", "name": "Expenditure"},
                                 {"stacking": False, "data": report[2], "type": "line", "name": "Income"}],
                      "yAxis": [{"title": {"text": "Expenditure & Income"}}], "chart": {"renderTo": "chart"},
                      "xAxis": [{"categories": report[0], "title": {"text": "Dates"}}],
                      "title": {"text": title}}]
            chart = json.dumps(chart)

    return render(request, 'Statistics/owner.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'form': form,
        'chart': chart,
    })


@login_required
@group_required(Admin)
def contracts(request):
    pass


@login_required
@group_required(Admin)
def attachments(request):
    pass

Statistic/templates/Statistics/accident.html
{% extends "Statistics/statistics_base.html" %}
{% block navbar_title %} General Payments {% endblock %}
{% block sidebar_accident %}active{% endblock %}
{% block sidebar_back %}
    {% if chart %}
        {% url 'Statistic:accident' %}
    {% else %}
        {% url 'Statistic:home' %}
    {% endif %}
{% endblock %}
{% block chart_block %}
    {% if chart %}
        <script type="text/javascript">
            {% autoescape off %}
                var _chartit_hco_array = {{ chart }};
            {% endautoescape %}
        </script>
        <script src="/static/js/chartloader.js" type="text/javascript"></script>
    {% endif %}
{% endblock %}

{% block content %}
    {% if not chart %}
        <div class="container">
            <form class="form-horizontal" style="width: 400px;" method="POST">
                {% csrf_token %}
                <table style="background: #ededff" class="table table-bordered">
                    <colgroup>
                        <col class="col1">
                        <col class="col2">
                    </colgroup>
                    <tbody>
                    {{ form.as_table }}
                    </tbody>
                </table>
                <button class="btn btn-success" type="submit">View Chart</button>
            </form>
        </div>
    {% endif %}
    {% if chart %}
        <div id='chart'></div>
    {% endif %}
{% endblock %}

Statistic/templates/Statistics/general.html
{% extends "Statistics/statistics_base.html" %}
{% block navbar_title %} General Payments {% endblock %}
{% block sidebar_general %}active{% endblock %}
{% block sidebar_back %}
    {% if chart %}
        {% url 'Statistic:general' %}
    {% else %}
        {% url 'Statistic:home' %}
    {% endif %}
{% endblock %}
{% block chart_block %}
    {% if chart %}
        <script type="text/javascript">
            {% autoescape off %}
                var _chartit_hco_array = {{ chart }};
            {% endautoescape %}
        </script>
        <script src="/static/js/chartloader.js" type="text/javascript"></script>
    {% endif %}
{% endblock %}

{% block content %}
    {% if not chart %}
        <div class="container">
            <form class="form-horizontal" style="width: 400px;" method="POST">
                {% csrf_token %}
                <table style="background: #ededff" class="table table-bordered">
                    <colgroup>
                        <col class="col1">
                        <col class="col2">
                    </colgroup>
                    <tbody>
                    {{ form.as_table }}
                    </tbody>
                </table>
                <button class="btn btn-success" type="submit">View Chart</button>
            </form>
        </div>
    {% endif %}
    {% if chart %}
        <div id='chart'></div>
    {% endif %}
{% endblock %}

Statistic/templates/Statistics/home.html
{% extends "home_base.html" %}

{% block navbar_title %} Statistic {% endblock %}
{% block sidebar_statistic %}active{% endblock %}
{% block navbar_statistic %}active{% endblock %}
{% block sidebar_back %}{% url 'Home:home' %}{% endblock %}
{% block content %}
<div class="row-fluid">
    <div class="span4">
        <h2>General Statistic</h2>

        <p>You can access all the statistics about the income and expenditure of the whole company and see the charts of them.
        <p><a class="btn" href="{% url 'Statistic:general' %}">View financial reports &raquo;</a></p>
    </div>
    <!--/span-->
    <div class="span4">
        <h2>User Statistic</h2>
        <p>You can review the statistic of your employee to see how much activity the dealer has in the company.</p>
        <p><a class="btn" href="{% url 'Statistic:user' %}">Statistic of an employee &raquo;</a></p>
    </div>
    <!--/span-->
    <div class="span4">
        <h2>Owner Statistic</h2>
        <p>You can access the financial issues of one specific Customer. Using this section you will access all the money
            gave and delivered by the company to an Customer.</p>
        <p><a class="btn" href="{% url 'Statistic:owner' %}"> Statistic of a customer &raquo;</a></p>
    </div>
</div><!--/row-->
{% endblock %}

Statistic/templates/Statistics/owner.html
{% extends "Statistics/statistics_base.html" %}
{% block navbar_title %} Owner Payments {% endblock %}
{% block sidebar_owner %}active{% endblock %}
{% block sidebar_back %}
    {% if chart %}
        {% url 'Statistic:owner' %}
    {% else %}
        {% url 'Statistic:home' %}
    {% endif %}
{% endblock %}
{% block chart_block %}
    {% if chart %}
        <script type="text/javascript">
            {% autoescape off %}
                var _chartit_hco_array = {{ chart }};
            {% endautoescape %}
        </script>
        <script src="/static/js/chartloader.js" type="text/javascript"></script>
    {% endif %}
{% endblock %}

{% block content %}
    {% if not chart %}
        <a>
        <div class="container">
            <form class="form-horizontal" style="width: 400px;" method="POST">
                {% csrf_token %}
                <table style="background: #ededff" class="table table-bordered">
                    <colgroup>
                        <col class="col1">
                        <col class="col2">
                    </colgroup>
                    <tbody>
                    {{ form.as_table }}
                    </tbody>
                </table>
                <button class="btn btn-success" type="submit">View Chart</button>
            </form>
        </div>
    {% endif %}
{% if chart %}
    <div id='chart'></div>
{% endif %}
{% endblock %}

Statistic/templates/Statistics/statistics_base.html
{% extends "base.html" %}
{% block sidebar_back %}{% url 'Statistic:home' %}{% endblock %}
{% block navbar_statistic %}active{% endblock %}
{% block sidebar_content %}
    <li class="{% block sidebar_general %}{% endblock %}"><a href="{% url 'Statistic:general' %}">General Payments</a>
    </li>
    <li class="{% block sidebar_user %}{% endblock %}"><a href="{% url 'Statistic:user' %}">User Payments</a></li>
    <li class="{% block sidebar_owner %}{% endblock %}"><a href="{% url 'Statistic:owner' %}">Owner Payments</a></li>
    <li class="{% block sidebar_accident %}{% endblock %}"><a href="{% url 'Statistic:accident' %}">Count Accident</a></li>
{% endblock %}

Statistic/templates/Statistics/user.html
{% extends "Statistics/statistics_base.html" %}
{% block navbar_title %} User Payments {% endblock %}
{% block sidebar_user %}active{% endblock %}
{% block sidebar_back %}
    {% if chart %}
        {% url 'Statistic:user' %}
    {% else %}
        {% url 'Statistic:home' %}
    {% endif %}
{% endblock %}
{% block chart_block %}
    {% if chart %}
        <script type="text/javascript">
            {% autoescape off %}
                var _chartit_hco_array = {{ chart }};
            {% endautoescape %}
        </script>
        <script src="/static/js/chartloader.js" type="text/javascript"></script>
    {% endif %}
{% endblock %}

{% block content %}
    {% if not chart %}
        <a>
        <div class="container">
            <form class="form-horizontal" style="width: 400px;" method="POST">
                {% csrf_token %}
                <table style="background: #ededff" class="table table-bordered">
                    <colgroup>
                        <col class="col1">
                        <col class="col2">
                    </colgroup>
                    <tbody>
                    {{ form.as_table }}
                    </tbody>
                </table>
                <button class="btn btn-success" type="submit">View Chart</button>
            </form>
        </div>
    {% endif %}
{% if chart %}
    <div id='chart'></div>
{% endif %}
{% endblock %}