Accident/urls.py
__author__ = 'Behnam Hatami'

from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^home$', 'Accident.views.home', name="home"),
                       url(r'^create_accident$', 'Accident.views.create_accident', name='create_accident'),
                       url(r'^(?P<aid>\d+)/finalize$', 'Accident.views.finalize_accident', name='finalize_accident'),
                       url(r'^(?P<aid>\d+)/$', 'Accident.views.view_accident', name='view_accident'),
                       url(r'^$', 'Accident.views.accident', name='accident'),
)

Home/urls.py
__author__ = 'Behnam Hatami'

from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^home$', 'Home.views.home', name="home"),
                       )

Insurance/urls.py
__author__ = 'Behnam Hatami'

from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^home$', 'Insurance.views.home', name='home'),
                       url(r'^contract/(?P<cid>\d+)/vehicle/(?P<vid>\d+)/history$', 'Insurance.views.history_vehicle',
                           name='history_vehicle'),
                       url(r'^contract/(?P<cid>\d+)/vehicle/(?P<vid>\d+)/edit$', 'Insurance.views.edit_vehicle',
                           name='edit_vehicle'),
                       url(r'^contract/(?P<cid>\d+)/vehicle/(?P<vid>\d+)$', 'Insurance.views.view_vehicle',
                           name='view_vehicle'),

                       url(r'^contract/(?P<cid>\d+)/person/(?P<pid>\d+)/history$', 'Insurance.views.history_person',
                           name='history_person'),
                       url(r'^contract/(?P<cid>\d+)/person/(?P<pid>\d+)/edit$', 'Insurance.views.edit_person',
                           name='edit_person'),
                       url(r'^contract/(?P<cid>\d+)/person/(?P<pid>\d+)$', 'Insurance.views.view_person',
                           name='view_person'),

                       url(r'^contract/(?P<cid>\d+)/company/(?P<mid>\d+)/history$', 'Insurance.views.history_company',
                           name='history_company'),
                       url(r'^contract/(?P<cid>\d+)/company/(?P<mid>\d+)/edit$', 'Insurance.views.edit_company',
                           name='edit_company'),
                       url(r'^contract/(?P<cid>\d+)/company/(?P<mid>\d+)$', 'Insurance.views.view_company',
                           name='view_company'),

                       url(r'^contract/(?P<cid>\d+)/history$', 'Insurance.views.history_contract',
                           name='history_contract'),
                       url(r'^contract/(?P<cid>\d+)/edit$', 'Insurance.views.edit_contract', name='edit_contract'),
                       url(r'^contact/(?P<cid>\d+)/accidents$', 'Insurance.views.list_accident', name='list_accident'),
                       url(r'^contract/(?P<cid>\d+)/print$', 'Insurance.views.print_contract', name='print_contract'),
                       url(r'^contract/(?P<cid>\d+)$', 'Insurance.views.view_contract', name='view_contract'),
                       url(r'^contract/create$', 'Insurance.views.create_contract', name='create_contract'),
                       url(r'^contract/search_contract$', 'Insurance.views.search_contract', name='search_contract'),
                       url(r'^contract$', 'Insurance.views.contract', name='contract'),
)

Pasargad/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Pasargad.views.home', name='home'),
    # url(r'^Pasargad/', include('Pasargad.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('Account.urls', namespace='Account')),
    url(r'^insurance/', include('Insurance.urls', namespace='Insurance')),
    url(r'^management/', include('Management.urls', namespace='Management')),
    url(r'^Accident/', include('Accident.urls', namespace='Accident')),
    url(r'^Statistic/', include('Statistic.urls', namespace='Statistic')),
    url(r'^', include('Home.urls', namespace='Home')),
)

Home/models.py
from django.db import models

# Create your models here.

Home/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from Pasargad.helper import *


def home(request):
    error_message = ''

    if not request.user.is_authenticated():
        if request.method.upper() == 'POST':
            username = request.POST['username']
            password = request.POST['password']

            user = authenticate(username=username, password=password)
            if user is None:
                error_message = 'The username or password you entered is incorrect.'
            elif not user.is_active:
                error_message = 'The user has been disabled by admin.'

            if error_message != '':
                return render(request, 'Home/Signin.html', {
                    'error_message': error_message,
                })
            login(request, user)
            if request.GET.__contains__("next"):
                return redirect(request.GET.get("next"))
            else:
                return redirect('Home:home')
        else:
            return render(request, 'Home/Signin.html')
    else:
        print(get_user_name(request))
        return render(request, 'Home/home.html', {
            'user_name': get_user_name(request),
            'security': get_security(request)
        })

Insurance/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from Accident.forms import accident_form_show

from Insurance.models import *
from Insurance.forms import *
from Pasargad.helper import *

import os
import StringIO

from xhtml2pdf import pisa

from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render
from django.template.loader import get_template
from django.template.context import Context
from django.utils.html import escape


def fetch_resources(uri, rel):
    """
    Callback to allow xhtml2pdf/reportlab to retrieve Images,Stylesheets, etc.
    `uri` is the href attribute from the html link element.
    `rel` gives a relative path, but it's not used here.

    """
    if uri.startswith(settings.MEDIA_URL):
        path = os.path.join(settings.MEDIA_ROOT,
                            uri.replace(settings.MEDIA_URL, ""))
    elif uri.startswith(settings.STATIC_URL):
        path = os.path.join(settings.STATIC_ROOT,
                            uri.replace(settings.STATIC_URL, ""))
    else:
        path = os.path.join(settings.STATIC_ROOT,
                            uri.replace(settings.STATIC_URL, ""))

        if not os.path.isfile(path):
            path = os.path.join(settings.MEDIA_ROOT,
                                uri.replace(settings.MEDIA_URL, ""))

            if not os.path.isfile(path):
                raise Exception(
                    'media urls must start with %s or %s' % (
                        settings.MEDIA_ROOT, settings.STATIC_ROOT))

    return path


def render_to_pdf(template_src, context_dict):
    """Function to render html template into a pdf file"""
    template = get_template(template_src)
    context = Context(context_dict)
    html = template.render(context)
    result = StringIO.StringIO()

    pdf = pisa.pisaDocument(StringIO.StringIO(html.encode("UTF-8")),
                            dest=result,
                            encoding='UTF-8',
                            link_callback=fetch_resources)
    if not pdf.err:
        response = HttpResponse(result.getvalue(),
                                mimetype='application/pdf')

        return response

    return HttpResponse('We had some errors<pre>%s</pre>' % escape(html))


@login_required
@group_required(Secretory, Expert)
def home(request):
    return render(request, 'Insurance/home.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
    })


@login_required
@group_required(Secretory, Expert)
def contract(request):
    form = None
    if request.method.upper() == 'POST':
        form = Contract_search(request.POST)
        if form.is_valid():
            return redirect('Insurance:view_contract', cid=form.cleaned_data['contract'])
    else:
        form = Contract_search()

    return render(request, 'Insurance/enter_contract.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'form': form,
    })


@login_required
@group_required(Secretory, Expert)
def view_contract(request, cid):
    print('here')
    contract_info = get_object_or_404(Contract, pk=cid).get_last_info()
    form = Contract_info_form_show(instance=contract_info)

    return render(request, 'Insurance/contract.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'property_list': get_property_list(contract_info, form, title='Contract', id=cid),
        'contract_info': get_contract_info(cid),
    })


@login_required
@group_required(Secretory)
def print_contract(request, cid):
    """Build briefing packages format and export as HTML and PDF."""
    contract_info = get_object_or_404(Contract, pk=cid).get_last_info()
    vehicle = contract_info.contract.vehicle
    vehicle_owner = vehicle.vehicle_owner
    person = vehicle_owner.person
    company = vehicle_owner.company

    property_set = [get_property_list(contract_info, Contract_info_form_show(), id=cid, title='Contract'),
                    get_property_list(vehicle.get_last_info(), Vehicle_info_form_show(), id=vehicle.id, title='Vehicle'),
                    get_property_list(vehicle_owner, vehicle_owner_form_show(), id=vehicle_owner.id,
                                      title='Vehicle Owner')]

    if person != None:
        property_set.append(get_property_list(person.get_last_info(), Person_info_form_show(), id=person.id, title='Person'))

    if company != None:
        property_set.append(get_property_list(company.get_last_info(), Company_info_form_show(), id=company.id, title='Company'))

    # return render(request, 'Insurance/pdf.html', {
    #     'property_set': property_set,
    # })

    return render_to_pdf('Insurance/pdf.html', {
        'property_set': property_set,
    })


@login_required
@group_required(Secretory, Expert)
def list_accident(request, cid):
    contract = get_object_or_404(Contract, pk=cid)
    queryset = contract.vehicle.accident_set.all().order_by('-date')[:10]
    form_head = accident_form_show()
    property_set = []
    for item in queryset:
        property_set.append(get_property_list(item, form_head, id=item.id))

    return render(request, 'Insurance/list_accident.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'form_head': form_head,
        'property_set': property_set,
        'notify_message': "There isn't any accident " if len(property_set) == 0 else '',
    })


@login_required
@group_required(Secretory)
def search_contract(request):
    form = None
    form_head = None
    property_set = []
    if request.method.upper() == 'POST':
        form = search_contract_form(request.POST)
        if form.is_valid():
            form_head = Contract_info_form_show()
            chassis_number = form.cleaned_data['chassis_number']
            queryset = Contract.objects.all().filter(vehicle__vehicle_info__chassis_number=chassis_number).distinct()
            for item in queryset:
                property_set.append(get_property_list(item.get_last_info(), form_head, id=item.id))
            form = None
    else:
        form = search_contract_form();

    return render(request, 'Insurance/search_contract.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'form': form,
        'form_head': form_head,
        'property_set': property_set,
        'notify_message': "Thers isn't any vehicle with with this Chasiss number" if len(
            property_set) == 0 and form == None else '',
    })


@login_required
@group_required(Secretory)
def edit_contract(request, cid):
    success_message = None
    notify_message = None
    form = None

    contract_info = get_object_or_404(Contract, pk=cid).get_last_info()
    if request.method.upper() == 'POST':
        payment = Payment(cost=0, date=timezone.now(), dealer=request.user,
                          owner=contract_info.contract.vehicle.vehicle_owner)
        payment.save()
        contract_instance = Contract_info(contract=contract_info.contract, creation_date=timezone.now(),
                                          contract_type='A', payment=payment)
        form = Contract_info_form_edit(request.POST, instance=contract_instance)
        if form.is_valid():
            new_contract_info = form.save(commit=False)
            payment.cost = compute_different_payment(new_contract_info, contract_info)
            payment.save()
            new_contract_info.save()
            notify_message = 'you {} {} Rials at {}.'.format('paid' if payment.cost >= 0 else 'received',
                                                             abs(payment.cost),
                                                             payment.date)
            success_message = "Changes applied."
        else:
            payment.delete()
    else:
        form = Contract_info_form_edit(instance=contract_info)

    return render(request, 'Insurance/edit_contract.html', {
        'user_name': get_user_name(request),
        'security': get_security(request),
        'contract_info': get_contract_info(cid),
        'form': form,
        'notify_message': notify_message,
        'success_message': success_message,
    })


@login_required
@group_required(Secretory)
def create_contract(request):
    form = None
    success_message = ''
    notify_message = ''
    hidden_table = dict()
    next_level = level = 0
    type_of_page = ''
    vehicle_owner = None
    vehicle = None
    contract_id = None

    if request.method.upper() == 'GET':
        form = Create_contract_first()
        next_level = 1
    else:
        level = int(request.POST['level'])
        next_level = level + 1

        if level == 1:
            form = Create_contract_first(request.POST)
            if form.is_valid():
                type_of_page = form.cleaned_data['drop_down']

                if type_of_page == 'Person':
                    form = Person_info_form_edit()
                elif type_of_page == 'Company':
                    form = Company_info_form_edit()
                else:
                    form = Get_vehicle_owner()
            else:
                next_level = 1

        elif level == 2:
            type_of_page = request.POST['type_of_page']
            if type_of_page == 'Person':
                person = Person()
                person.save()
                person_info_instance = Person_info(person=person, creation_date=timezone.now())
                form = Person_info_form_edit(request.POST, instance=person_info_instance)
                if form.is_valid():
                    form.save()
                    vehicle_owner = Vehicle_owner(person=person)
                    vehicle_owner.save()
                else:
                    person.delete()
                    next_level = level
            elif type_of_page == 'Company':

Insurance/templates/Insurance/company.html
{% extends "Insurance/insurance_base.html" %}
{% block navbar_title %} View Company {% endblock %}
{% block sidebar_company %}active{% endblock %}
{% block sidebar_contract_link %}{% url 'Insurance:view_contract' contract_info.contract.id %}{% endblock %}
{% block sidebar_back %}{% url 'Insurance:view_contract' contract_info.contract.id %}{% endblock %}

{% block content %}
    <div class="container">
        <form class="form-horizontal" style="width: 500px;" method="POST">
            {% csrf_token %}
            <table style="background: #ededff" class="table table-bordered">
                <colgroup>
                    <col class="col1">
                    <col class="col2">
                </colgroup>
                <tbody>
                <tr>
                    <td><label>ID Number</label></td>
                    <td><label>{{ property_list.id }}</label></td>
                </tr>
                {% for property in property_list %}
                    <tr>
                        <td><label>{{ property.0 }}</label></td>
                        <td><label>{{ property.1|linebreaksbr }}</label></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% if security.Secretory %}
                <a class="btn btn-warning" type="submit"
                   href="{% url 'Insurance:edit_company' contract_info.contract.id contract_info.company.id %}">Edit</a>
            {% endif %}
            <a class="btn btn-info" type="submit"
               href="{% url 'Insurance:history_company' contract_info.contract.id contract_info.company.id %}">History</a>
        </form>
    </div>
{% endblock %}

Insurance/templates/Insurance/contract.html
{% extends "Insurance/insurance_base.html" %}
{% block navbar_title %} View Company {% endblock %}
{% block sidebar_contract %}active{% endblock %}
{% block sidebar_back %}{% url 'Insurance:contract' %}{% endblock %}

{% block content %}
    <div class="container">
        <form class="form-horizontal" style="width: 500px;" method="POST">
            {% csrf_token %}
            <h3>{{ property_list.title }}</h3>
            <table style="background: #ededff" class="table table-bordered">
                <colgroup>
                    <col class="col1">
                    <col class="col2">
                </colgroup>
                <tbody>
                <tr>
                    <td><label>ID Number</label></td>
                    <td><label>{{ property_list.id }}</label></td>
                </tr>
                {% for property in property_list %}
                    <tr>
                        <td><label>{{ property.0 }}</label></td>
                        <td><label>{{ property.1|linebreaksbr }}</label></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            {% if security.Secretory %}
                <a class="btn btn-warning" type="submit"
                   href="{% url 'Insurance:edit_contract' contract_info.contract.id %}">Edit</a>

                <a class="btn btn-primary" type="submit"
                   href="{% url 'Insurance:print_contract' contract_info.contract.id %}">Print</a>
            {% endif %}
            <a class="btn btn-info" type="submit"
               href="{% url 'Insurance:history_contract' contract_info.contract.id %}">History</a>
            <hr>
            <h3>Other Links</h3>
            <table style="background: #ededff" class="table table-bordered">
                <colgroup>
                    <col class="col1">
                </colgroup>
                <tbody>
                {% if contract_info.vehicle %}
                    <tr>
                        <td><label><a
                                href="{% url 'Insurance:view_vehicle' contract_info.contract.id contract_info.vehicle.id %}">Vehicle: {{ contract_info.vehicle }}</a></label>
                        </td>
                    </tr>
                {% endif %}

                {% if contract_info.person %}
                    <tr>
                        <td><label><a
                                href="{% url 'Insurance:view_person' contract_info.contract.id contract_info.person.id %}">Vehicle
                            Owner: {{ contract_info.person }}</a></label></td>
                    </tr>
                {% endif %}

                {% if contract_info.company %}
                    <tr>
                        <td><label><a
                                href="{% url 'Insurance:view_company' contract_info.contract.id contract_info.company.id %}">Vehicle
                            Owner: {{ contract_info.company }}</a></label></td>
                    </tr>
                {% endif %}
                <tr>
                    <td>
                        <label><a href="{% url 'Insurance:list_accident' contract_info.contract.id %}">Latest Accident</a></label>
                    </td>
                </tr>
                </tbody>
            </table>
        </form>
    </div>
{% endblock %}

Insurance/templates/Insurance/edit_company.html
{% extends "Insurance/insurance_base.html" %}
{% block navbar_title %} Edit Company {% endblock %}
{% block sidebar_company %}active{% endblock %}
{% block sidebar_back %}
    {% url 'Insurance:view_company' contract_info.contract.id contract_info.company.id %}{% endblock %}


{% block content %}
    {% if form %}
        <div class="container">
            <form class="form-horizontal" style="width: 400px;" method="POST">
                {% csrf_token %}
                <hr>
                <table style="background: #ededff" class="table table-bordered">
                    <colgroup>
                        <col class="col1">
                        <col class="col2">
                    </colgroup>
                    <tbody>
                    {{ form.as_table }}
                    </tbody>
                </table>
                <button class="btn btn-success" type="submit">Save</button>
                <a class="btn btn-danger"
                   href="{% url 'Insurance:view_company' contract_info.contract.id contract_info.company.id %}">Cancel</a>
                <a class="btn btn-warning"
                   href="{% url 'Insurance:edit_company' contract_info.contract.id contract_info.company.id %}">Reset</a>
            </form>
        </div>
    {% endif %}
{% endblock %}

Insurance/templates/Insurance/edit_contract.html
{% extends "Insurance/insurance_base.html" %}
{% block navbar_title %} Edit Company {% endblock %}
{% block sidebar_contract %}active{% endblock %}
{% block sidebar_back %}{% url 'Insurance:view_contract' contract_info.contract.id %}{% endblock %}


{% block content %}
    {% if form %}
        <div class="container">
            <form class="form-horizontal" style="width: 400px;" method="POST">
                {% csrf_token %}
                <hr>
                <table style="background: #ededff" class="table table-bordered">
                    <colgroup>
                        <col class="col1">
                        <col class="col2">
                    </colgroup>
                    <tbody>
                    {{ form.as_table }}
                    </tbody>
                </table>
                <button class="btn btn-success" type="submit">Save</button>
                <a class="btn btn-danger"
                   href="{% url 'Insurance:view_contract' contract_info.contract.id %}">Cancel</a>
                <a class="btn btn-warning"
                   href="{% url 'Insurance:edit_contract' contract_info.contract.id %}">Reset</a>
            </form>
        </div>
    {% endif %}
{% endblock %}

Insurance/templates/Insurance/edit_person.html
{% extends "Insurance/insurance_base.html" %}
{% block navbar_title %} Edit Person {% endblock %}
{% block sidebar_person %}active{% endblock %}
{% block sidebar_back %}
    {% url 'Insurance:view_person' contract_info.contract.id contract_info.person.id %}{% endblock %}

{% block content %}
    {% if form %}
        <div class="container">
            <form class="form-horizontal" style="width: 400px;" method="POST">
                {% csrf_token %}
                <hr>
                <table style="background: #ededff" class="table table-bordered">
                    <colgroup>
                        <col class="col1">
                        <col class="col2">
                    </colgroup>
                    <tbody>
                    {{ form.as_table }}
                    </tbody>
                </table>
                <button class="btn btn-success" type="submit">Save</button>
                <a class="btn btn-danger"
                   href="{% url 'Insurance:view_person' contract_info.contract.id contract_info.person.id %}">Cancel</a>
                <a class="btn btn-warning"
                   href="{% url 'Insurance:edit_person' contract_info.contract.id contract_info.person.id %}">Reset</a>
            </form>
        </div>
    {% endif %}
{% endblock %}

Insurance/templates/Insurance/edit_vehicle.html
{% extends "Insurance/insurance_base.html" %}
{% block navbar_title %} Edit Person {% endblock %}
{% block sidebar_vehicle %}active{% endblock %}
{% block sidebar_back %}
    {% url 'Insurance:view_vehicle' contract_info.contract.id contract_info.vehicle.id %}{% endblock %}

{% block content %}
    {% if form %}
        <div class="container">
            <form class="form-horizontal" style="width: 400px;" method="POST">
                {% csrf_token %}
                <hr>
                <table style="background: #ededff" class="table table-bordered">
                    <colgroup>
                        <col class="col1">
                        <col class="col2">
                    </colgroup>
                    <tbody>
                    {{ form.as_table }}
                    </tbody>
                </table>
                <button class="btn btn-success" type="submit">Save</button>
                <a class="btn btn-danger"
                   href="{% url 'Insurance:view_vehicle' contract_info.contract.id contract_info.vehicle.id %}">Cancel</a>
                <a class="btn btn-warning"
                   href="{% url 'Insurance:edit_vehicle' contract_info.contract.id contract_info.vehicle.id %}">Reset</a>
            </form>
        </div>
    {% endif %}
{% endblock %}

Insurance/templates/Insurance/enter_contract.html
{% extends "Insurance/insurance_base.html" %}
{% block navbar_title %} Edit Company {% endblock %}
{% block sidebar_contract %}active{% endblock %}
{% block sidebar_back %}{% url 'Insurance:home' %}{% endblock %}


{% block content %}
    {% if form %}
        <div class="container">
            <form class="form-horizontal" style="width: 400px;" method="POST">
                {% csrf_token %}
                <hr>
                <table style="background: #ededff" class="table table-bordered">
                    <colgroup>
                        <col class="col1">
                        <col class="col2">
                    </colgroup>
                    <tbody>
                    {{ form.as_table }}
                    </tbody>
                </table>
                <button class="btn btn-success" type="submit">View</button>
                <a class= "btn btn-warning" href="{% url 'Insurance:search_contract' %}" >Forget</a>
            </form>
        </div>
    {% endif %}
{% endblock %}

Insurance/templates/Insurance/home.html
{% extends "home_base.html" %}

{% block navbar_title %} Insurance {% endblock %}
{% block navbar_insurance %}active{% endblock %}
{% block sidebar_insurance %}active{% endblock %}
{% block sidebar_back %}{% url 'Home:home' %}{% endblock %}
{% block content %}
    <div class="row-fluid">
        <div class="span4">
            <h2>View Contract</h2>
            <p>Simply view an existing contract by entering the contract-id on the insurance card.</p>
            <p><a class="btn" href="{% url 'Insurance:contract' %}">View contract &raquo;</a></p>
        </div>
        <!--/span-->
        {% if security.Secretory %}
            <div class="span4">
                <h2>Create Contract</h2>
                <p>Create a new contract or an extention using the system. Enter the details of the owner and the vehicle and the system will
                calculate the amount of money that should be payed, only in four steps.</p>
                <p><a class="btn" href="{% url 'Insurance:create_contract' %}">Create contract &raquo;</a></p>
            </div>
        {% endif %}
        <!--/span-->
    </div><!--/row-->
{% endblock %}

Insurance/templates/Insurance/list_accident.html
{% extends 'Insurance/insurance_base.html' %}
{% block navbar_title %}List Of Accident{% endblock %}
{% block sidebar_contract %}active{% endblock %}
{% block sidebar_back %}{% url 'Insurance:home' %}{% endblock %}
{% block content %}
    {% if not notify_message %}
        <hr>
        <table style="background: #ededff" class="table table-bordered">
            <colgroup>
                <col class="col1">
                <col class="col2">
                <col class="col3">
                <col class="col4">
            </colgroup>
            <thead>
            <tr>
                <th><b>ID</b></th>
                {% for field in form_head %}
                    <th><b>{{ field.label|capfirst }}</b></th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for property_list in property_set %}
                <tr>
                    <td>
                        <a href="{% url 'Accident:view_accident' property_list.id %}">{{ property_list.id  }}</a>
                    </td>
                    {% for property in property_list %}
                        <td>
                            <lable>{{ property.1|linebreaksbr }}</lable>
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

Insurance/templates/Insurance/person.html
{% extends "Insurance/insurance_base.html" %}
{% block navbar_title %} View Person {% endblock %}
{% block sidebar_persons %}active{% endblock %}
{% block sidebar_contract_link %}{% url 'Insurance:view_contract' contract_info.contract.id %}{% endblock %}
{% block sidebar_back %}{% url 'Insurance:view_contract' contract_info.contract.id %}{% endblock %}

{% block content %}
    <div class="container">
        <form class="form-horizontal" style="width: 400px;" method="POST">
            {% csrf_token %}
            <table style="background: #ededff" class="table table-bordered">
                <colgroup>
                    <col class="col1">
                    <col class="col2">
                </colgroup>
                <tbody>
                <tr>
                    <td><label>ID Number</label></td>
                    <td><label>{{ property_list.id }}</label></td>
                </tr>
                {% for property in property_list %}
                    <tr>
                        <td><label>{{ property.0 }}</label></td>
                        <td><label>{{ property.1|linebreaksbr }}</label></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% if security.Secretory %}
                <a class="btn btn-warning" type="submit"
                   href="{% url 'Insurance:edit_person' contract_info.contract.id contract_info.person.id %}">Edit</a>
            {% endif %}
            <a class="btn btn-info" type="submit"
               href="{% url 'Insurance:history_person' contract_info.contract.id contract_info.person.id %}">History</a>
        </form>
    </div>
{% endblock %}